services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: ssant/ndvi
    environment:
      - DATABASE_URL
      - EE_PROJECT_ID
      - EE_PRIVATE_KEY_ID
      - EE_PRIVATE_KEY
      - EE_CLIENT_EMAIL
      - EE_CLIENT_ID
    command: ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8080"]
    ports:
      - "8080:8080"
volumes:
  pgdata: