"""initial

Revision ID: 239a17031e4c
Revises: 
Create Date: 2022-06-19 14:54:00.795625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239a17031e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
