"""fields

Revision ID: 918ff90d2ca5
Revises: 922dc9c7944f
Create Date: 2022-06-05 21:37:23.511436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918ff90d2ca5'
down_revision = '922dc9c7944f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('geojson', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'geojson')
    # ### end Alembic commands ###
