"""initial

Revision ID: 922dc9c7944f
Revises: 
Create Date: 2022-06-05 21:36:17.035077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922dc9c7944f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
